name: Notify via Discord

on:
  watch:
    types: [started]
  fork:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            ${{ 
              github.event_name == 'watch' && '${{ github.actor }} starred the One-Captcha!' || 
              github.event_name == 'fork' && '${{ github.actor }} forked the One-Captcha!' || 
              github.event_name == 'issues' && format('${{ github.actor }} created an issue on One-Captcha!**Title:** {0}**Body:** {1}', github.event.issue.title, github.event.issue.body) || 
              github.event_name == 'pull_request' && format('${{ github.actor }} created a pull request on One-Captcha!**Title:** {0}**Body:** {1}', github.event.pull_request.title, github.event.pull_request.body)
            }}
