name: Notify via Discord

on:
  watch:
    types: [started]
  fork:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            ${{ 
              github.event_name == 'watch' && format('{0} starred the One-Captcha!', github.actor) || 
              github.event_name == 'fork' && format('{0} forked the One-Captcha!', github.actor) || 
              github.event_name == 'issues' && format('{0} created an issue on One-Captcha. **Title:** {1}', github.actor, github.event.issue.title) || 
              github.event_name == 'pull_request' && format('{0} created a pull request on One-Captcha. **Title:** {1}', github.actor, github.event.pull_request.title)
            }}
